name: instrunet_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  audio_metadata_reader: ^1.4.2
  build_runner: ^2.5.4
  darq: ^2.1.0
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_data: ^2.0.0
  flutter_hooks: ^0.21.3+1
  http: ^1.5.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  shared_preferences: ^2.5.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
